language: csharp
mono: none
sudo: required
dist: xenial
addons:
    snaps:
      - name: dotnet-sdk
        confinement: classic
        channel: 3.1/stable
install:
   - export PATH="$PATH:/home/travis/.dotnet/tools"
   - export PATH="$PATH:$HOME/.local/bin"
   - sudo snap alias dotnet-sdk.dotnet dotnet  
global:
   - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
   - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
   - chmod -R a+x scripts
script:
   - ./scripts/dotnet-build.sh
   - ./scripts/dotnet-test.sh
deploy:
  provider: script
  script:
   - ./scripts/dotnet-publish.sh
   - sudo ./scripts/docker-publish-travis.sh
   - ./scripts/after-success.sh
  on:
    branch: master

