language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
services:
  - docker
script:
  - dotnet restore
  - dotnet build
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
after_success:
  - docker --version
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - eval $(aws ecr get-login --region us-east-1)
  - docker build -t NosCoreBot .
  - docker tag noscorebot:latest 703970026174.dkr.ecr.us-west-2.amazonaws.com/noscorebot:latest
  - docker push 703970026174.dkr.ecr.us-west-2.amazonaws.com/noscorebot:latest
  