language: csharp
dist: xenial
sudo: required
mono: none
dotnet: 2.2
branches:
  only:
    - master
global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
before_script:
  - chmod -R a+x scripts
script:
  - ./scripts/dotnet-build.sh
  - ./scripts/dotnet-test.sh
  - ./scripts/dotnet-publish.sh
  - ./scripts/docker-publish-travis.sh
after_success:
  - ./scripts/after-success.sh